package com.automation.runners;

import io.cucumber.testng.AbstractTestNGCucumberTests;
import io.cucumber.testng.CucumberOptions;
import org.testng.annotations.DataProvider;

/**
 * Failed Test Runner - Re-runs failed scenarios from previous execution
 * Uses the rerun.txt file generated by main runner
 */
@CucumberOptions(
    features = "@target/cucumber-reports/rerun.txt",
    glue = {"com.automation.stepdefinitions", "com.automation.hooks"},
    plugin = {
        "pretty",
        "html:target/cucumber-reports/rerun-report.html",
        "json:target/cucumber-reports/rerun-report.json",
        "com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:"
    },
    monochrome = true
)
public class FailedTestRunner extends AbstractTestNGCucumberTests {

    @Override
    @DataProvider(parallel = false)
    public Object[][] scenarios() {
        return super.scenarios();
    }
}
